"""User-facing localized strings for the Telegram bot.

The pilot is mixed-language (Spanish/English, maybe more), so anything the bot
says on its own (welcome, quota notice) keys off the Telegram client's
``language_code``. Unknown codes fall back to a bilingual EN+ES message rather
than assuming English. The coach's *own* replies are generated by the agent in
the user's language and are unaffected by this module."""
from __future__ import annotations

_WELCOME = {
    "en": (
        "Hi — I'm your coach. I'm here to help you reach your goals, whatever "
        "they are: a race, a habit, a hard change you've been putting off. "
        "Tell me what you're working toward and what's getting in the way."
    ),
    "es": (
        "Hola — soy tu coach. Estoy aquí para ayudarte a alcanzar tus metas, "
        "sean cuales sean: una carrera, un hábito, un cambio difícil que vienes "
        "postergando. Cuéntame qué quieres lograr y qué se te interpone."
    ),
    "pt": (
        "Olá — sou o seu coach. Estou aqui para ajudar você a alcançar os seus "
        "objetivos, sejam quais forem: uma prova, um hábito, uma mudança difícil "
        "que você vem adiando. Conte o que você quer conquistar e o que atrapalha."
    ),
}


def _normalize(language_code: str | None) -> str:
    """Map a Telegram ``language_code`` (e.g. ``en-US``) to a base language key."""
    if not language_code:
        return ""
    return language_code.split("-", 1)[0].strip().lower()


def welcome_text(language_code: str | None) -> str:
    """Localized welcome. Unknown/missing language → bilingual EN+ES fallback."""
    lang = _normalize(language_code)
    if lang in _WELCOME:
        return _WELCOME[lang]
    return f"{_WELCOME['en']}\n\n{_WELCOME['es']}"


def quota_reached_text(language_code: str | None, limit: int) -> str:
    """Localized 'daily limit reached' notice. Resets at midnight."""
    lang = _normalize(language_code)
    en = (
        f"You've reached your daily limit of {limit} messages. "
        f"It resets at midnight — talk to me again then."
    )
    es = (
        f"Has alcanzado tu límite diario de {limit} mensajes. "
        f"Se reinicia a medianoche — hablamos entonces."
    )
    if lang == "es":
        return es
    if lang == "en":
        return en
    return f"{en}\n\n{es}"
